import type { Metadata } from 'next';
import { CalculatorScaffold } from '@/components/content/CalculatorScaffold';
import { QuiltSizeCalculator } from '@/components/calculators/QuiltSizeCalculator';
import { Section, FAQ } from '@/components/content/sections';
import { CALCULATOR_BY_ID } from '@/lib/registry';
import { generatePageMetadata } from '@/lib/seo';
const meta = CALCULATOR_BY_ID['quilt-size-calculator']!;
export const metadata: Metadata = generatePageMetadata({ title: meta.title, description: meta.description, path: meta.route, keywords: meta.keywords, ogType: 'article' });
export default function Page() { return <CalculatorScaffold calculatorId="quilt-size-calculator" interactive={<QuiltSizeCalculator />}>
<Section id="methodology" title="How the size calculation works" eyebrow="Methodology"><p>The finished quilt is the sum of its blocks, the sashing between them and the borders around the outside:</p><ul><li>Width = (blocks across × block size) + sashing between blocks + (2 × border)</li><li>Length = (blocks down × block size) + sashing between blocks + (2 × border)</li></ul><p>Sashing sits <em>between</em> blocks, so a row of five blocks has four sashing strips. We then compare your finished size to standard US quilt sizes and show the closest match.</p></Section>
<Section id="example" title="Worked example" eyebrow="See it in numbers"><p><strong>12″</strong> blocks in a <strong>5 × 6</strong> grid, no sashing or border:</p><ul><li>Width = 5 × 12 = 60″</li><li>Length = 6 × 12 = 72″</li><li>30 blocks total → closest standard size: Throw / Lap</li></ul></Section>
<Section id="reference" title="Standard US quilt sizes" eyebrow="Reference"><table><thead><tr><th>Size</th><th>Approx. width</th><th>Approx. length</th></tr></thead><tbody><tr><td>Baby / Crib</td><td>36 in</td><td>52 in</td></tr><tr><td>Throw / Lap</td><td>52 in</td><td>60 in</td></tr><tr><td>Twin</td><td>70 in</td><td>90 in</td></tr><tr><td>Full / Double</td><td>84 in</td><td>90 in</td></tr><tr><td>Queen</td><td>90 in</td><td>100 in</td></tr><tr><td>King</td><td>108 in</td><td>100 in</td></tr></tbody></table><p>Sizes vary by mattress depth and desired drop — treat them as a starting point.</p></Section>
<Section id="faq" title="Frequently asked questions"><FAQ items={[{q:'Should I use finished or unfinished block size?',a:'Use the finished block size — the size after the block is sewn into the quilt (typically ½″ smaller than the unfinished block on each dimension).'},{q:'Does sashing go around the outside too?',a:'This tool places sashing only between blocks. For sashing around the outside edge as well, add that amount to the border field.'},{q:'How do I plan the backing once I know the size?',a:'Take the finished width and length into the quilt backing calculator to get backing yardage, and the binding calculator for the edge.'}]} /></Section>
<Section id="sources" title="Sources & assumptions" eyebrow="Transparency"><ul><li>Uses finished block dimensions.</li><li>Sashing is counted between blocks only.</li><li>Borders are added equally to all four sides.</li><li>Standard sizes are approximate and depend on mattress and drop.</li></ul></Section>
</CalculatorScaffold>; }
