import type { Metadata } from 'next';
import { CalculatorScaffold } from '@/components/content/CalculatorScaffold';
import { BackingCalculator } from '@/components/calculators/BackingCalculator';
import { Section, FAQ } from '@/components/content/sections';
import { CALCULATOR_BY_ID } from '@/lib/registry';
import { generatePageMetadata } from '@/lib/seo';
const meta = CALCULATOR_BY_ID['quilt-backing-calculator']!;
export const metadata: Metadata = generatePageMetadata({ title: meta.title, description: meta.description, path: meta.route, keywords: meta.keywords, ogType: 'article' });
export default function Page() { return <CalculatorScaffold calculatorId="quilt-backing-calculator" interactive={<BackingCalculator />}>
<Section id="methodology" title="How the backing calculation works" eyebrow="Methodology"><p>Your quilt back needs to be larger than the quilt top so it can be loaded onto a frame and survive the take-up of quilting. We add your <strong>overhang</strong> to every side:</p><ul><li>Backing width = quilt width + (2 × overhang)</li><li>Backing length = quilt length + (2 × overhang)</li></ul><p>Because quilting cotton comes in a fixed usable width (often about 42″), a normal-sized quilt back is pieced from full-width <strong>panels</strong> seamed together. We test both seam directions — panels running the length of the quilt, or rotated to run across it — and keep whichever uses the least fabric. Directional prints skip the rotation option so your pattern always runs the right way.</p><p>Each panel’s cut length includes a seam allowance at every join. We then convert the total length pulled off the bolt into yards and round <strong>up</strong> to the next quarter yard, so you never come up short at the cutting counter.</p></Section>
<Section id="example" title="Worked example" eyebrow="See it in numbers"><p>A <strong>60″ × 80″</strong> quilt with a <strong>4″</strong> overhang on 42″ fabric:</p><ul><li>Backing needed: 68″ × 88″</li><li>68″ ÷ 42″ = 1.62 → <strong>2 panels</strong>, seams running vertically</li><li>Each panel cut 88″ + seam allowance ≈ 88.5″; two panels ≈ 177″</li><li>177″ ÷ 36 = 4.92 yd exact → buy <strong>5 yd</strong></li></ul></Section>
<Section id="reference" title="Common fabric widths & overhangs" eyebrow="Reference"><table><thead><tr><th>Fabric</th><th>Usable width</th><th>Best for</th></tr></thead><tbody><tr><td>Quilting cotton</td><td>42–44 in</td><td>Most quilts (pieced back)</td></tr><tr><td>Wide backing</td><td>108 in</td><td>Seamless backs up to king</td></tr><tr><td>Extra-wide muslin</td><td>90–120 in</td><td>Utility & practice quilts</td></tr></tbody></table><p>Overhang guidance: hand or domestic machine quilting needs about 2–3″ per side; long-arm quilters usually ask for 4″ per side. When in doubt, ask your quilter first.</p></Section>
<Section id="faq" title="Frequently asked questions"><FAQ items={[{q:'Should I buy extra beyond the recommendation?',a:'The recommended amount already rounds up and includes overhang and seam allowance. If your cutter is generous with straightening or you want insurance against a crooked cut, add another quarter yard.'},{q:'Why did the seam direction change when I resized the quilt?',a:'We always pick the orientation that uses less fabric. As the quilt’s proportions change, the cheaper direction can flip between vertical and horizontal seams.'},{q:'What if I use 108″ wide backing?',a:'Enter 108 as the fabric width. For most quilts one width will cover the whole back with no seam, and the tool will tell you so.'},{q:'Does this include batting?',a:'No — this calculates the backing fabric only. Batting is usually cut to the same size as the backing.'}]} /></Section>
<Section id="sources" title="Sources & assumptions" eyebrow="Transparency"><ul><li>Panels are cut the full usable width of the fabric and seamed side by side.</li><li>Default usable width 42″; adjust to match your specific fabric.</li><li>Seam allowance is added to each panel join; the default is ¼″.</li><li>Purchase yardage is rounded up to the next ¼ yard.</li><li>This tool gives fabric estimates for planning — always confirm against your quilter’s requirements before buying.</li></ul></Section>
</CalculatorScaffold>; }
