import type { Metadata } from 'next';
import { CalculatorScaffold } from '@/components/content/CalculatorScaffold';
import { YardageCalculator } from '@/components/calculators/YardageCalculator';
import { Section, FAQ } from '@/components/content/sections';
import { CALCULATOR_BY_ID } from '@/lib/registry';
import { generatePageMetadata } from '@/lib/seo';
const meta = CALCULATOR_BY_ID['fabric-yardage-calculator']!;
export const metadata: Metadata = generatePageMetadata({ title: meta.title, description: meta.description, path: meta.route, keywords: meta.keywords, ogType: 'article' });
export default function Page() { return <CalculatorScaffold calculatorId="fabric-yardage-calculator" interactive={<YardageCalculator />}>
<Section id="methodology" title="How the yardage calculation works" eyebrow="Methodology"><p>When you need several pieces of the same size, the trick is fitting as many as possible across the fabric’s width before starting a new row:</p><ul><li>Pieces per row = fabric width ÷ piece width (rounded down)</li><li>Rows = total pieces ÷ pieces per row (rounded up)</li><li>Fabric length = rows × piece length</li></ul><p>We add your seam allowance to every edge, then test the pieces both as-entered and rotated 90°, keeping the layout that uses the least fabric — unless the fabric is directional and can’t be turned. The result is converted to yards and rounded up to the next quarter yard.</p></Section>
<Section id="example" title="Worked example" eyebrow="See it in numbers"><p><strong>4</strong> pieces of <strong>18″ × 22″</strong> on 42″ fabric (no seam allowance):</p><ul><li>42″ ÷ 18″ = 2 pieces per row</li><li>4 ÷ 2 = 2 rows</li><li>2 × 22″ = 44″ → 1.22 yd → buy <strong>1.25 yd</strong></li></ul></Section>
<Section id="reference" title="Typical fabric widths" eyebrow="Reference"><table><thead><tr><th>Fabric type</th><th>Usable width</th></tr></thead><tbody><tr><td>Quilting cotton</td><td>42–44 in</td></tr><tr><td>Apparel cotton / linen</td><td>54–58 in</td></tr><tr><td>Home decor</td><td>54 in</td></tr><tr><td>Wide backing</td><td>108 in</td></tr></tbody></table><p>“Usable width” is the fabric between the selvedges, minus any unusable printed edge — always a little less than the bolt’s stated width.</p></Section>
<Section id="faq" title="Frequently asked questions"><FAQ items={[{q:'Should I include seam allowance?',a:'If you entered finished sizes, yes — set a seam allowance per edge (often ¼–⅝″). If your piece sizes already include seam allowance, set it to 0.'},{q:'Why did rotating the pieces change the amount?',a:'Turning pieces 90° can pack more per row and waste less length. We automatically pick the cheaper layout unless you mark the fabric as directional.'},{q:'What if a piece is wider than the fabric?',a:'Then it can’t be cut in one piece — you’ll see a warning. Choose a wider fabric or plan to piece it together.'}]} /></Section>
<Section id="sources" title="Sources & assumptions" eyebrow="Transparency"><ul><li>Simple grid layout; pieces are not nested or tilted to save fabric.</li><li>Seam allowance is added to all four edges of every piece.</li><li>Directional fabric disables the rotated layout.</li><li>Purchase yardage rounds up to the next ¼ yard.</li></ul></Section>
</CalculatorScaffold>; }
