import Link from 'next/link';
import type { Metadata } from 'next';
import { CALCULATORS, HUBS, calculatorsInHub } from '@/lib/registry';
import { SITE } from '@/lib/site';
import { generatePageMetadata } from '@/lib/seo';

export const metadata: Metadata = generatePageMetadata({ title: `${SITE.name} — ${SITE.tagline}`, description: SITE.description, path: '/' });
const STEPS = [{ n:'01',t:'Enter your measurements',d:'Inches or centimeters — switch anytime without losing your numbers.'},{n:'02',t:'See the exact math',d:'We separate the true requirement from a shop-friendly amount to buy.'},{n:'03',t:'Cut with confidence',d:'A visual cutting plan shows panels, seams and layout before you cut.'}];
export default function HomePage(){const featured=CALCULATORS.slice(0,6);return <>
<section className="relative overflow-hidden border-b border-line"><div className="pointer-events-none absolute inset-0 bg-ruler-grid [background-size:24px_24px] opacity-60"/><div className="container-wide relative grid gap-10 py-16 sm:py-24 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div className="animate-rise"><p className="chip">Free calculators · No sign-up · US-first</p><h1 className="mt-5 font-display text-5xl font-semibold leading-[1.05] tracking-tight text-ink sm:text-6xl">Fabric math<br/><span className="text-terracotta">without the guesswork.</span></h1><p className="mt-6 max-w-lg font-sans text-lg leading-relaxed text-ink-soft">Plan backing, binding, yardage and cutting layouts for your sewing and quilting projects. Every calculator is deterministic, tested and shows its work.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={HUBS.quilting.route} className="btn-primary">Start with quilting →</Link><Link href="/calculation-methodology/" className="btn-ghost">How the math works</Link></div></div><div className="relative animate-rise [animation-delay:120ms]"><div className="card rotate-1 p-6 shadow-lift"><div className="ruler-tape mb-4" aria-hidden/><p className="font-sans text-xs font-semibold uppercase tracking-wider text-ink-faint">Quilt backing · 60 × 80 in</p><p className="mt-2 flex items-baseline gap-2"><span className="tnum font-display text-6xl font-semibold text-teal">5.0</span><span className="font-mono text-lg text-ink-faint">yd</span></p><div className="mt-4 grid grid-cols-3 gap-2 font-mono text-sm">{[['Panels','2'],['Seam','Vertical'],['Exact','4.92 yd']].map(([k,v])=><div key={k} className="rounded-lg border border-line bg-paper-deep/40 px-3 py-2"><span className="block text-[10px] uppercase tracking-wide text-ink-faint">{k}</span><span className="tnum text-ink">{v}</span></div>)}</div><svg viewBox="0 0 200 130" className="mt-4 w-full" aria-hidden><rect x="1" y="1" width="198" height="128" rx="8" fill="#fffdf8" stroke="#ddd0ba"/><rect x="20" y="15" width="160" height="100" rx="3" fill="rgba(196,89,58,0.08)" stroke="rgba(196,89,58,0.5)"/><rect x="40" y="30" width="120" height="70" rx="3" fill="rgba(31,90,82,0.14)" stroke="rgba(31,90,82,0.7)"/><line x1="100" y1="15" x2="100" y2="115" stroke="#c4593a" strokeWidth="1.5" strokeDasharray="4 3"/></svg></div></div></div></section>
<section className="container-wide py-16"><div className="flex items-end justify-between gap-4"><div><p className="font-sans text-xs font-semibold uppercase tracking-wider text-terracotta">The tools</p><h2 className="mt-1 text-3xl font-semibold text-ink sm:text-4xl">Six calculators, zero guesswork</h2></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featured.map((c,i)=><Link key={c.id} href={c.route} className="group card flex flex-col p-6 transition hover:-translate-y-1 hover:shadow-lift" style={{animationDelay:`${i*40}ms`}}><span className="font-mono text-xs text-ink-faint">{HUBS[c.hub].title.replace(' Calculators','').replace(' & Reference','')}</span><h3 className="mt-2 font-display text-xl font-medium text-ink group-hover:text-teal">{c.title}</h3><p className="mt-2 flex-1 font-sans text-sm leading-relaxed text-ink-soft">{c.purpose}</p><span className="mt-4 inline-flex items-center gap-1 font-sans text-sm font-semibold text-terracotta">Open calculator <span aria-hidden className="transition group-hover:translate-x-1">→</span></span></Link>)}</div></section>
<section className="border-y border-line bg-paper-deep/40"><div className="container-wide py-16"><h2 className="text-3xl font-semibold text-ink sm:text-4xl">How it works</h2><div className="mt-8 grid gap-6 md:grid-cols-3">{STEPS.map(s=><div key={s.n} className="relative"><span className="font-mono text-sm font-semibold text-terracotta">{s.n}</span><h3 className="mt-2 font-display text-xl font-medium text-ink">{s.t}</h3><p className="mt-2 font-sans text-sm leading-relaxed text-ink-soft">{s.d}</p></div>)}</div></div></section>
<section className="container-wide py-16"><h2 className="text-3xl font-semibold text-ink sm:text-4xl">Browse by project</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{Object.values(HUBS).map(hub=><Link key={hub.id} href={hub.route} className="group card flex items-center justify-between gap-4 p-6 transition hover:border-teal/40"><div><h3 className="font-display text-2xl font-medium text-ink group-hover:text-teal">{hub.title}</h3><p className="mt-1 font-sans text-sm text-ink-soft">{hub.blurb}</p><p className="mt-3 font-mono text-xs text-ink-faint">{calculatorsInHub(hub.id).length} tool{calculatorsInHub(hub.id).length===1?'':'s'}</p></div><span aria-hidden className="text-2xl text-terracotta transition group-hover:translate-x-1">→</span></Link>)}</div></section>
</>;}
