import type { Metadata } from 'next';
import { CalculatorScaffold } from '@/components/content/CalculatorScaffold';
import { BindingCalculator } from '@/components/calculators/BindingCalculator';
import { Section, FAQ } from '@/components/content/sections';
import { CALCULATOR_BY_ID } from '@/lib/registry';
import { generatePageMetadata } from '@/lib/seo';
const meta = CALCULATOR_BY_ID['quilt-binding-calculator']!;
export const metadata: Metadata = generatePageMetadata({ title: meta.title, description: meta.description, path: meta.route, keywords: meta.keywords, ogType: 'article' });
export default function Page() { return <CalculatorScaffold calculatorId="quilt-binding-calculator" interactive={<BindingCalculator />}>
<Section id="methodology" title="How the binding calculation works" eyebrow="Methodology"><p>Binding wraps the entire edge of your quilt, so first we find the <strong>perimeter</strong>:</p><ul><li>Perimeter = 2 × (width + length)</li><li>Binding needed = perimeter + a corner, join and overlap allowance</li></ul><p>Binding is made from strips cut across the width of the fabric (WOF) and joined end to end. We divide the binding length by your usable fabric width to get the number of <strong>strips</strong>, then multiply by the strip’s cut width to find how much fabric length that consumes. Finally we convert to yards and round up to the next eighth of a yard.</p></Section>
<Section id="example" title="Worked example" eyebrow="See it in numbers"><p>A <strong>60″ × 80″</strong> quilt, 2½″ strips, 42″ fabric, 10″ allowance:</p><ul><li>Perimeter = 2 × (60 + 80) = 280″; + 10″ = 290″ of binding</li><li>290″ ÷ 42″ = 6.9 → <strong>7 strips</strong></li><li>7 × 2.5″ = 17.5″ of fabric → 0.49 yd → buy <strong>0.5 yd</strong></li></ul></Section>
<Section id="reference" title="Binding strip widths" eyebrow="Reference"><table><thead><tr><th>Cut width</th><th>Style</th><th>Finished look</th></tr></thead><tbody><tr><td>2¼ in</td><td>Double-fold</td><td>Narrow, crisp edge</td></tr><tr><td>2½ in</td><td>Double-fold</td><td>Most popular, easy to sew</td></tr><tr><td>2¾ in</td><td>Double-fold</td><td>Fuller edge, hides thicker batting</td></tr></tbody></table><p>Cutting on the straight grain (WOF) is assumed here. Bias binding for curved edges uses more fabric and is calculated differently.</p></Section>
<Section id="faq" title="Frequently asked questions"><FAQ items={[{q:'How much overlap allowance should I use?',a:'Around 10–15″ covers mitred corners, the diagonal joins between strips and the closing overlap where the binding meets itself. Larger quilts sit at the higher end.'},{q:'Is this straight-grain or bias binding?',a:'This calculates straight-grain (cross-grain) binding, which suits quilts with straight edges. Rounded corners or scalloped edges need bias binding and more fabric.'},{q:'Why round to an eighth of a yard?',a:'Binding uses little fabric, so an eighth-yard increment avoids over-buying while still guaranteeing enough for every strip.'}]} /></Section>
<Section id="sources" title="Sources & assumptions" eyebrow="Transparency"><ul><li>Straight-grain (WOF) binding; strips cut across the usable fabric width.</li><li>Strip count rounds up so the total strip length always covers the perimeter plus allowance.</li><li>Purchase yardage rounds up to the next ⅛ yard.</li><li>Bias binding and very thick battings may need more — treat this as a planning estimate.</li></ul></Section>
</CalculatorScaffold>; }
