import type { Metadata } from 'next';
import Link from 'next/link';
import { ContentPage } from '@/components/content/ContentPage';
import { LastReviewed } from '@/components/content/sections';
import { generatePageMetadata } from '@/lib/seo';

export const metadata: Metadata = generatePageMetadata({ title:'Calculation Methodology', description:'The formulas, assumptions and rounding rules behind every YardageLab calculator, explained in plain language.', path:'/calculation-methodology/' });
export default function Page(){return <ContentPage title="Calculation Methodology" intro="Every YardageLab calculator is deterministic and explainable. Here is exactly how the math works." breadcrumbName="Methodology" breadcrumbPath="/calculation-methodology/">
<h3>Core principles</h3><ul><li><strong>Exact vs. purchase.</strong> We always show the precise mathematical requirement and a separate, conservative amount to buy. Material requirements are never rounded down.</li><li><strong>One base unit.</strong> All lengths convert to millimeters internally using exact constants (1 in = 25.4 mm, 1 yd = 914.4 mm), so results are identical whether you work in inches or centimeters.</li><li><strong>Stated assumptions.</strong> Each result lists the defaults it used, and important ones — fabric width, overhang, seam allowance — are yours to override.</li></ul>
<h3><Link href="/quilting/backing-calculator/">Quilt backing</Link></h3><p>Backing width and length add your overhang to both sides of the quilt. The back is pieced from full-width panels; we test seams running each direction and keep the cheaper one (directional prints skip rotation). Each panel’s cut length includes a seam allowance per join. Total length becomes yards, rounded up to the next ¼ yard.</p>
<h3><Link href="/quilting/binding-calculator/">Quilt binding</Link></h3><p>Perimeter = 2 × (width + length), plus a corner/join/overlap allowance. Strips are cut across the fabric width; strip count = binding length ÷ fabric width, rounded up. Fabric length = strips × strip width, converted to yards and rounded up to the next ⅛ yard.</p>
<h3><Link href="/quilting/quilt-size-calculator/">Quilt size</Link></h3><p>Finished size = (blocks × block size) + sashing between blocks + borders on both sides. Sashing is counted between blocks only. We match the result to the closest standard US size.</p>
<h3><Link href="/sewing/fabric-yardage-calculator/">Fabric yardage</Link></h3><p>Pieces per row = fabric width ÷ piece width (rounded down); rows = quantity ÷ pieces per row (rounded up); fabric length = rows × piece length. Seam allowance is added to every edge, and we keep the cheaper of the as-entered and rotated layouts. Rounded up to the next ¼ yard.</p>
<h3><Link href="/home-decor/curtain-fabric-calculator/">Curtain fabric</Link></h3><p>Gathered width = window width × fullness. Fabric widths = gathered width ÷ fabric width (rounded up, at least one per panel). Cut length = drop + header + hem, rounded up to a whole pattern repeat when specified. Total = widths × cut length, rounded up to the next ¼ yard.</p>
<h3><Link href="/conversions/fabric-unit-converter/">Unit conversion</Link></h3><p>Values pass through the millimeter base unit with exact constants, making conversions reversible. Imperial results also show a fraction rounded to the nearest eighth.</p>
<h3>A note on estimates</h3><p>These tools produce planning estimates. Fabric shrinks, prints skew, and cutting isn’t perfect — when a project is precious, buy a little extra and confirm against your own pattern or quilter’s requirements before cutting.</p><div className="mt-8"><LastReviewed date="2026-08-23" /></div>
</ContentPage>}
